#!/usr/bin/env python3
"""Find rules that several lists claim, and say which one actually wins.

A domain can legitimately appear in two lists when both route it the same way - the derived
aggregates are unions, so overlap with their sources is expected. What is worth catching is a rule
claimed by lists that route it *differently*, because then the outcome is decided by list order and
nobody can see it from the lists themselves (the fast.com case: proxy.list on the gateways and
mmc.list on the Hubs, so a Netflix speed test left through the US pool while netflix.com left through
Hong Kong).

usage:
  audit-duplicates.py            # conflicts only (exit 1 when any exist)
  audit-duplicates.py --all      # also list same-policy overlaps
  audit-duplicates.py --list r1,r2
"""
import argparse
import collections
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOCS = pathlib.Path.home() / 'Library/Mobile Documents/iCloud~com~nssurge~inc/Documents'
# Consumer rule files, in the order Surge evaluates them. Gateway files already carry the collapsed
# policy (Proxy -> entry), which is exactly what decides the outcome there.
CONSUMERS = ['Common.dconf', 'Common-Rules.dconf', 'Home-SMART-rules.dconf', 'Office-SMART-rules.dconf']
# The two Hubs consume a different, much smaller set; this mirrors /etc/mihomo/config.yaml (2026-10-10)
# and is verified against the running config by ops-manual §2 / bump-rule-release.py --hubs.
HUB_CONSUMER = {
    'ai-apple.list': 'AI-Apple', 'ai-claude.list': 'AI-Claude', 'ai-chat.list': 'AI-OpenAI',
    'ai-google.list': 'AI-Google', 'ai.list': 'AI', 'us.list': 'AI', 'ben.list': 'Work-US',
    'video-proxy.list': 'Proxy', 'twitter.list': 'AI', 'agg-tiktok.list': 'Work-US',
    'mmc.list': 'Work-US',
}
GENERATED = ('GENERATED by scripts/build-agg.py', 'VENDORED from')
# Declared precedence layers (specific, generic): the specific list must win, so an overlap here is
# intended and the audit only asserts the order. Anything else that shares a domain with a different
# target in the same consumer is an owner that needs deciding.
LAYERS = {('ai-apple.list', 'ai.list'), ('ai-claude.list', 'ai.list'),
          ('ai-chat.list', 'ai.list'), ('ai-google.list', 'ai.list')}
# Shared third-party SaaS that Claude and OpenAI both call. Claimed by both vendor lists on purpose:
# ai-claude.list precedes ai-chat.list in every consumer, so these ride the Claude identity. Listed
# explicitly so that a *new* overlap between the two still fails the gate.
SHARED_SAAS = {
    'DOMAIN-SUFFIX,api.statsig.com', 'DOMAIN-SUFFIX,events.statsigapi.net', 'DOMAIN-SUFFIX,featuregates.org',
    'DOMAIN,cdn.workos.com', 'DOMAIN,forwarder.workos.com', 'DOMAIN,setup.workos.com',
    'DOMAIN,images.workoscdn.com', 'DOMAIN,workos.imgix.net', 'DOMAIN-SUFFIX,workos.com',
    'DOMAIN-SUFFIX,sentry.io', 'DOMAIN-SUFFIX,stripe.com', 'DOMAIN-SUFFIX,stripecdn.com',
    'DOMAIN-SUFFIX,hcaptcha.com', 'DOMAIN-SUFFIX,hcaptcha.net', 'DOMAIN-SUFFIX,js.stripe.com',
    'DOMAIN-SUFFIX,cloudflareinsights.com', 'DOMAIN-SUFFIX,challenges.cloudflare.com',
    'DOMAIN,rum.browser-intake-datadoghq.com',
}
RULE_RE = re.compile(r'^(RULE-SET|DOMAIN-SET),(\S+?)/([A-Za-z0-9._-]+\.list),([^,]+)')


def lists_rules():
    rules = {}
    for path in sorted(ROOT.glob('*.list')):
        text = path.read_text(encoding='utf-8')
        kind = 'hand' if not any(mark in text for mark in GENERATED) else 'generated'
        body = [l.strip() for l in text.splitlines()
                if l.strip() and not l.lstrip().startswith(('#', ';', '//'))]
        rules[path.name] = (kind, body)
    return rules


def consumer_order(name):
    """[(list name, policy)] in evaluation order, or None when the file is unavailable."""
    path = DOCS / name
    if not path.exists():
        return None
    out = []
    for line in path.read_text(encoding='utf-8').splitlines():
        m = RULE_RE.match(line)
        if m:
            out.append((m.group(3), m.group(4)))
    return out or None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--all', action='store_true', help='also list same-policy overlaps')
    args = ap.parse_args()

    rules = lists_rules()
    owners = collections.defaultdict(set)
    for name, (_kind, body) in rules.items():
        for rule in body:
            owners[rule].add(name)

    consumers = {}
    for name in CONSUMERS:
        order = consumer_order(name)
        if order:
            consumers[name] = order
    consumers['hub:/etc/mihomo'] = list(HUB_CONSUMER.items())

    kinds = {name: kind for name, (kind, _) in rules.items()}
    # A rule is ambiguous only when, *inside one consumer*, the lists that claim it route it
    # differently - that is what makes the outcome depend on list order. Compare the collapsed
    # gateway policy (entry) with the phone policy is meaningless, so never compare across files.
    hand_conflicts, generated_overlaps, layering, same_policy = [], [], [], []
    for rule, who in owners.items():
        if len(who) < 2:
            continue
        per_consumer = {}
        for cname, order in consumers.items():
            present = [(i, lst, pol) for i, (lst, pol) in enumerate(order) if lst in who]
            if len(present) < 2 or len({pol for _, _, pol in present}) < 2:
                continue
            i, lst, pol = min(present)
            per_consumer[cname] = (lst, pol, sorted({p for _, _, p in present}))
        if not per_consumer:
            same_policy.append((rule, sorted(who)))
            continue
        hand = all(kinds[l] == 'hand' for l in who)
        ordered = sorted(who)
        pairs = [(a, b) for i, a in enumerate(ordered) for b in ordered[i + 1:]]
        # ai.list carries the same shared SaaS, so it counts as part of the same claim (and must lose).
        vendor_pair = ({l for l in who} <= {'ai-claude.list', 'ai-chat.list', 'ai.list'}
                       and rule in SHARED_SAAS)
        if vendor_pair:
            bucket = layering
        elif pairs and all(pair in LAYERS or (pair[1], pair[0]) in LAYERS for pair in pairs):
            bucket = layering
            winners = {lst for lst, _pol, _o in per_consumer.values()}
            bad = [f for f in winners if f != 'ai.list' and (f, 'ai.list') not in LAYERS]
            for consumer, (lst, _pol, _o) in per_consumer.items():
                if lst == 'ai.list' and any((f, 'ai.list') in LAYERS for f in who):
                    bad.append('generic ai.list wins in ' + consumer)
            if bad:
                print('  !! 分层顺序错误: %s (%s)' % (rule[:50], '; '.join(sorted(set(bad))[:2])))
                bucket = hand_conflicts
        else:
            bucket = hand_conflicts if hand else generated_overlaps
        bucket.append((rule, who, per_consumer))

    def show(items, title):
        print('\n%s（%d 条）' % (title, len(items)))
        groups = collections.defaultdict(list)
        for rule, who, per_consumer in items:
            groups[tuple(sorted(who))].append((rule, per_consumer))
        for key, rows in sorted(groups.items(), key=lambda kv: -len(kv[1])):
            print('  ■ %s   %d 条' % ('  vs  '.join(key), len(rows)))
            for rule, per_consumer in rows[:4]:
                detail = []
                for cname, (lst, pol, others) in per_consumer.items():
                    short = (cname.replace('Common-Rules.dconf', '手机').replace('Common.dconf', '通用')
                             .replace('Home-SMART-rules.dconf', '网关home').replace('Office-SMART-rules.dconf', '网关office')
                             .replace('hub:/etc/mihomo', '中枢'))
                    if short in ('手机', '中枢', '网关home'):
                        detail.append('%s: %s(%s) 胜 %s' % (short, lst, pol, '/'.join(o for o in others if o != pol)))
                print('     %-44s %s' % (rule[:44], ' | '.join(detail)))
            if len(rows) > 4:
                print('     … 另 %d 条' % (len(rows) - 4))

    print('表 %d 张（手写 %d / 生成 %d）| 多表认领的规则 %d 条 | 同消费侧策略不一致 %d 条'
          % (len(rules), sum(k == 'hand' for k in kinds.values()), sum(k == 'generated' for k in kinds.values()),
             sum(len(v) for v in (hand_conflicts, generated_overlaps, layering)) + len(same_policy),
             len(hand_conflicts) + len(generated_overlaps) + len(layering)))
    if hand_conflicts:
        show(hand_conflicts, '■ 真正的双主人（手写表互相认领同一域名、路由不同、且非子集分层）——建议定归属')
    if layering:
        show(layering, '● 子集分层（专用表 ⊂ 通用表，故意的：专用表在前）')
    if generated_overlaps:
        show(generated_overlaps, '● 涉及生成表的重叠：顺序已定（一般是有意的），知情即可')
    if args.all and same_policy:
        print('\n● 策略一致的重复（不影响路由，仅供清理）：%d 条' % len(same_policy))
        for rule, who in same_policy[:20]:
            print('   %-46s %s' % (rule[:46], ', '.join(who)))
    return 1 if hand_conflicts else 0


if __name__ == '__main__':
    sys.exit(main())
