#!/usr/bin/env python3
"""Build the self-hosted aggregate lists that replace the per-service third-party rule sets.

Why: the gateways referenced 35 third-party rule sets directly. Each one is a separate upstream
dependency and a separate runtime fetch, and 33 of them were bound to the same policy anyway. The
aggregates below are built ONCE at commit time from the pinned upstream revisions, so the runtime
config only ever reads files from this repository.

Grouping rule: two source lists may be merged only if every consumer binds them to the same
policy AND the same RULE-SET flags. Concretely:
  * `agg-proxy.list`      Proxy (mobile) / 入口 (gateway); one flag set (extended-matching)
  * `agg-google.list`     AI-Google (mobile) / 入口 (gateway)
  * `agg-workus.list`     Work-US, extended-matching
  * `agg-workus-nr.list`  Work-US, no-resolve (Facebook/Instagram carry IP rules, so the flag matters)
  * `agg-direct.list`     DIRECT
`no-resolve` on a list without IP rules is a no-op, so those lists can join the flag-compatible
aggregate; lists that do carry IP rules keep their own flag group.

usage: build-agg.py [--check]   (writes the repo's agg-*.list; --check only reports drift)
"""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BM7_SHA = '83f37120c155f67c8eef43221dabe15cc3c95fec'
SEMP_SHA = '557dc2bbb71a6a1b47a23dc30156d3fe254f8c45'
BM7 = 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/%s/rule/Surge/%%s/%%s.list' % BM7_SHA
SEMP = 'https://raw.githubusercontent.com/Semporia/TikTok-Unlock/%s/Surge/TikTok.list' % SEMP_SHA

AGGREGATES = {
    'agg-proxy': ['AppleNews', 'AppleTV', 'Bing', 'Discord', 'Disney', 'Docker', 'GitHub',
                  'Netflix', 'Notion', 'OneDrive', 'PayPal', 'Pinterest', 'PlayStation', 'Telegram'],
    'agg-google': ['Gemini', 'Google', 'GoogleVoice', 'YouTube'],
    # TikTok 不能并进来：网关侧生成器 (home/office-smart-pilot.py 的 covered_work) 会把
    # TikTok.list 折到入口，而本组其它成员保持 Work-US —— 同一个聚合表在网关与手机上
    # 目标不一致，故 TikTok 两条（bm7 + Semporia）继续单独引用上游。
    'agg-workus': ['Adobe', 'LinkedIn', 'Reddit', 'Shopify', 'TruthSocial'],
    'agg-workus-nr': ['Facebook', 'Instagram'],
    'agg-direct': ['Apple', 'AppStore', 'iCloud', 'Speedtest'],
}
EXTRA_SEMP = {}  # Semporia's TikTok-unlock stays a standalone upstream reference
# Vendored verbatim from ruleset.skk.moe (no version in its URL, so it cannot be pinned):
# skk source path -> repo file
VENDOR = {
    'non_ip/microsoft.conf': 'skk-microsoft.list',
    'non_ip/microsoft_cdn.conf': 'skk-microsoft-cdn.list',
    'non_ip/apple_services.conf': 'skk-apple-services.list',
}
# Bare-domain file: DOMAIN-SET matches the domain and its subdomains, hence DOMAIN-SUFFIX here.
VENDOR_DOMAIN_SET = {'domainset/apple_cdn.conf': 'skk-apple-cdn.list'}


def fetch(url):
    out = subprocess.run(['/usr/bin/curl', '-fsSL', '-m', '45', url], capture_output=True, text=True)
    if out.returncode or not out.stdout.strip():
        raise RuntimeError('fetch failed: %s' % url)
    return out.stdout


def rules_of(text):
    return [line.strip() for line in text.splitlines()
            if line.strip() and not line.lstrip().startswith(('#', ';', '//'))]


def build_aggregate(name, sources):
    seen, merged, per_source = set(), [], {}
    for label, url in sources:
        rules = rules_of(fetch(url))
        added = 0
        for rule in rules:
            if rule not in seen:
                seen.add(rule)
                merged.append(rule)
                added += 1
        per_source[label] = {'rules': len(rules), 'new': added}
    # Deterministic output: sort by rule type then value, so a rebuild without upstream changes
    # produces a byte-identical file (the drift check depends on that).
    merged.sort(key=lambda r: (r.split(',')[0], r))
    header = ('# NAME: %s (generated)\n# GENERATED by scripts/build-agg.py; do not hand-edit.\n'
              '# Aggregated from pinned third-party revisions:\n%s' %
              (name, ''.join('#   %s -> %s\n' % (l, u) for l, u in sources)))
    return header + '\n'.join(merged) + '\n', per_source


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    report = {'aggregates': {}, 'vendored': {}, 'drift': []}
    for name, lists in AGGREGATES.items():
        sources = [(l, BM7 % (l, l)) for l in lists]
        if name in EXTRA_SEMP:
            sources.append(('Semporia/TikTok-Unlock', SEMP))
        text, per_source = build_aggregate(name, sources)
        target = ROOT / (name + '.list')
        report['aggregates'][name] = {'rules': len(rules_of(text)), 'sources': len(sources),
                                      'sha256': hashlib.sha256(text.encode()).hexdigest()[:16],
                                      'per_source': per_source}
        if args.check:
            if not target.exists() or target.read_text() != text:
                report['drift'].append(name + '.list')
        else:
            target.write_text(text, encoding='utf-8')
    for src, target_name in VENDOR.items():
        text = fetch('https://ruleset.skk.moe/List/' + src)
        rules = rules_of(text)
        keep = [l for l in text.splitlines() if l.lstrip().startswith('#')][:6]
        out = ('# VENDORED from https://ruleset.skk.moe/List/%s (AGPL-3.0, (c) Sukka).\n'
               '# Re-fetch with scripts/build-agg.py; content is unchanged apart from this header.\n'
               % src) + '\n'.join(keep) + '\n' + '\n'.join(rules) + '\n'
        target = ROOT / target_name
        report['vendored'][target_name] = {'rules': len(rules)}
        if args.check:
            if not target.exists() or target.read_text() != out:
                report['drift'].append(target_name)
        else:
            target.write_text(out, encoding='utf-8')
    for src, target_name in VENDOR_DOMAIN_SET.items():
        text = fetch('https://ruleset.skk.moe/List/' + src)
        # skk's domain sets use a leading dot (and sometimes '*') for "this domain and below".
        domains = []
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            domains.append(line.lstrip('.*'))
        out = ('# VENDORED from https://ruleset.skk.moe/List/%s (AGPL-3.0, (c) Sukka).\n'
               '# Bare-domain set: a Surge DOMAIN-SET matches the domain and its subdomains, so each\n'
               '# entry is emitted as DOMAIN-SUFFIX here (leading . or * stripped).\n' % src) + \
              '\n'.join('DOMAIN-SUFFIX,' + d for d in sorted(set(domains))) + '\n'
        target = ROOT / target_name
        report['vendored'][target_name] = {'rules': len(set(domains))}
        if args.check:
            if not target.exists() or target.read_text() != out:
                report['drift'].append(target_name)
        else:
            target.write_text(out, encoding='utf-8')
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 2 if report['drift'] else 0


if __name__ == '__main__':
    sys.exit(main())
