#!/usr/bin/env python3
"""Validate one Surge source and generate explicit Mihomo-compatible outputs."""
import argparse
import hashlib
import ipaddress
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
BASE_URL = 'https://raw.githubusercontent.com/hbs1313/surgerule/main/'
PORTABLE = {'DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR', 'IP-CIDR6', 'IP-ASN'}
SURGE_ONLY = {'USER-AGENT', 'SRC-IP'}
CATEGORIES = {'ai', 'work-us', 'proxy', 'client-direct', 'dedicated', 'client-source'}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def read_rules(text, source):
    rules = []
    for number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith(('#', '//', ';')):
            continue
        where = f'{source}:{number}'
        require('"' not in line and "'" not in line, f'{where}: quoted fields are outside the shared rule subset')
        parts = line.split(',')
        require(len(parts) >= 2 and all(p == p.strip() and p for p in parts), f'{where}: malformed fields')
        kind, value = parts[:2]
        require(kind in PORTABLE | SURGE_ONLY, f'{where}: unsupported rule type {kind}')
        if kind in {'IP-CIDR', 'IP-CIDR6', 'IP-ASN', 'SRC-IP'}:
            require(len(parts) in {2, 3} and (len(parts) == 2 or parts[2] == 'no-resolve'), f'{where}: unsupported IP options or embedded policy')
        else:
            require(len(parts) == 2, f'{where}: embedded policy or unsupported options')
        if kind in {'IP-CIDR', 'IP-CIDR6', 'SRC-IP'}:
            if kind != 'SRC-IP':
                require('/' in value, f'{where}: CIDR prefix is required')
            try:
                network = ipaddress.ip_network(value, strict=True)
            except ValueError as error:
                raise ValueError(f'{where}: invalid network') from error
            if kind != 'SRC-IP':
                require(network.version == (6 if kind == 'IP-CIDR6' else 4), f'{where}: address family mismatch')
        elif kind == 'IP-ASN':
            require(value.isascii() and value.isdecimal() and 0 < int(value) <= 4294967295, f'{where}: invalid ASN')
        elif kind in {'DOMAIN', 'DOMAIN-SUFFIX'}:
            require(len(value) <= 253 and all(re.fullmatch(r'[A-Za-z0-9_](?:[A-Za-z0-9_-]{0,61}[A-Za-z0-9_])?', label) for label in value.split('.')), f'{where}: invalid domain')
        else:
            require(not any(c.isspace() or ord(c) < 32 for c in value), f'{where}: invalid pattern')
        require(line not in rules, f'{where}: duplicate rule')
        rules.append(line)
    require(rules, f'{source}: empty source')
    return rules


def load_manifest(root):
    manifest = json.loads((root / 'routing.json').read_text())
    require(manifest.get('schema_version') == 1, 'routing.json: unsupported schema')
    catalog, order = manifest.get('lists'), manifest.get('rules')
    require(isinstance(catalog, dict) and catalog, 'routing.json: missing list catalog')
    require(set(catalog) == {p.stem for p in root.glob('*.list')}, 'routing.json: catalog must cover every .list exactly')
    for name, item in catalog.items():
        require(re.fullmatch(r'[a-z][a-z0-9-]*', name), f'invalid list name: {name}')
        require(isinstance(item, dict) and item.get('category') in CATEGORIES, f'{name}: invalid category')
        require(item.get('mihomo') in {'full', 'partial', 'none'}, f'{name}: missing portability decision')
        require(isinstance(item.get('description'), str) and item['description'], f'{name}: missing description')
        require((item['category'] == 'client-source') == (item['mihomo'] == 'none'), f'{name}: source-device rules must stay client-only')
    require(isinstance(order, list) and order, 'routing.json: missing order')
    names = []
    for row in order:
        require(isinstance(row, list) and len(row) == 2 and all(isinstance(x, str) for x in row), 'routing.json: invalid rule binding')
        name, policy = row
        require(name in catalog and name not in names, 'routing.json: duplicate or missing list binding')
        require(catalog[name]['mihomo'] == 'full', f'{name}: shared bindings require full compatibility')
        require(re.fullmatch(r'[A-Za-z][A-Za-z0-9_-]*', policy), f'{name}: invalid policy')
        names.append(name)
    return manifest


def render_yaml(rules):
    # JSON quoted scalars are valid YAML and avoid special-character ambiguity.
    return 'payload:\n' + ''.join('  - ' + json.dumps(rule, ensure_ascii=False) + '\n' for rule in rules)


def render_examples(order):
    preface = '# GENERATED by scripts/build-rules.py; merge into the existing configuration.\n'
    surge = preface + '# Shared business bindings only; retain local/private rules and third-party rules.\n[Rule]\n'
    ingress = preface + '# Define SMART-入口 privately. Keep domestic/private and metadata-only rules locally.\n[Rule]\n'
    hub = preface + '# No proxies, credentials, listeners, private routes or FINAL/MATCH are supplied.\nrule-providers:\n'
    for name, policy in order:
        suffix = ',extended-matching,update-interval=3600\n'
        surge += f'RULE-SET,{BASE_URL}{name}.list,{policy}' + suffix
        ingress += f'RULE-SET,{BASE_URL}{name}.list,SMART-入口' + suffix
        hub += (f'  canonical-{name}:\n    type: http\n    behavior: classical\n    format: yaml\n'
                f'    url: {BASE_URL}{name}.yaml\n    path: ./surgerule/{name}.yaml\n    interval: 3600\n')
    hub += 'rules:\n' + ''.join('  - ' + json.dumps(f'RULE-SET,canonical-{name},{policy}') + '\n' for name, policy in order)
    return {'examples/surge-shared.dconf': surge, 'examples/surge-smart-ingress.dconf': ingress, 'examples/mihomo-shared.yaml': hub}


def compile_repository(root):
    manifest = load_manifest(root)
    outputs, rows = {}, []
    for name, item in manifest['lists'].items():
        source = root / (name + '.list')
        rules = read_rules(source.read_text(), source.name)
        portable = [rule for rule in rules if rule.split(',', 1)[0] in PORTABLE]
        omitted = [rule for rule in rules if rule.split(',', 1)[0] not in PORTABLE]
        mode = item['mihomo']
        if mode == 'full':
            require(not omitted, f'{name}: full parity cannot omit Surge-only rules')
        elif mode == 'partial':
            require(portable and omitted and all(rule.startswith('USER-AGENT,') for rule in omitted), f'{name}: partial mode permits only explicit USER-AGENT omissions')
        else:
            require(all(rule.startswith('SRC-IP,') for rule in rules), f'{name}: client-only mode is reserved for source-device routing')
        if mode != 'none':
            outputs[name + '.yaml'] = render_yaml(portable)
        rows.append({'name': name, **item, 'source': name + '.list', 'surge_rules': len(rules),
                     'mihomo_file': name + '.yaml' if mode != 'none' else None,
                     'mihomo_rules': len(portable) if mode != 'none' else 0,
                     'excluded_types': sorted({rule.split(',', 1)[0] for rule in omitted}),
                     'excluded_count': len(omitted),
                     'active_rules_sha256': hashlib.sha256(('\n'.join(rules) + '\n').encode()).hexdigest()})
    outputs.update(render_examples(manifest['rules']))
    outputs['docs/catalog.json'] = json.dumps({'source_of_truth': '*.list + routing.json', 'lists': rows}, ensure_ascii=False, indent=2) + '\n'
    doc = '# 规则目录（自动生成）\n\n只修改根目录 `.list` 和 `routing.json`，不要手改 YAML 或本目录生成文件。\n\n'
    doc += '| 列表 | 分类 | Surge 条数 | Mihomo 条数 | 兼容性 | 用途 |\n|---|---|---:|---:|---|---|\n'
    for row in rows:
        compatibility = {'full': '完整', 'partial': '部分：USER-AGENT 留在 Surge', 'none': '仅本地源地址，不生成 Hub 规则'}[row['mihomo']]
        doc += f"| [{row['name']}](../{row['source']}) | {row['category']} | {row['surge_rules']} | {row['mihomo_rules']} | {compatibility} | {row['description']} |\n"
    doc += '\n“语法可用于 Mihomo”不代表应在境外 Hub 接管：国内直连与源设备规则仍由本地网关负责。\n'
    outputs['docs/catalog.md'] = doc
    return outputs


def synchronize(root, check):
    # Validate everything before writing anything; --check never writes.
    outputs = compile_repository(root)
    existing = {p.name for p in root.glob('*.yaml')}
    expected = {name for name in outputs if '/' not in name}
    require(not existing - expected, 'unexpected root YAML: ' + ', '.join(sorted(existing - expected)))
    stale = [name for name, text in outputs.items() if not (root / name).exists() or (root / name).read_text() != text]
    if check:
        require(not stale, 'generated files missing or stale: ' + ', '.join(stale))
    else:
        for name in stale:
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(outputs[name])
    return len(outputs), len(stale)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='validate all artifacts without writing')
    args = parser.parse_args()
    try:
        total, changed = synchronize(ROOT, args.check)
    except (ValueError, OSError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        return 1
    print(f'{"CHECK" if args.check else "BUILD"} OK: {total} generated files; {changed} {"stale" if args.check else "updated"}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
